const express = require("express");
const authRoutes = require("./auth.routes");
const userRoutes = require("./user.routes");
const companyRoutes = require("./company.routes");
const employeeRequestRoutes = require("./employeeRequest.routes");
const notificationRoutes = require("./notification.routes");
const attendanceRoutes = require("./attendance.routes");
const attendancePolicyRoutes = require("./attendancePolicy.routes");
const shiftRoutes = require("./shift.routes");
const holidayRoutes = require("./holiday.routes");
const leaveRoutes = require("./leave.routes");
const leaveTypeRoutes = require("./leaveType.routes");
const regularizationRoutes = require("./regularization.routes");
const weeklyOffPolicyRoutes = require("./weeklyOffPolicy.routes");
const leavePolicyRoutes = require("./leavePolicy.routes");
const departmentRoutes = require("./department.routes");
const designationRoutes = require("./designation.routes");
const reportingManagerRoutes = require("./reportingManager.routes");
const orgTreeRoutes = require("./orgTree.routes");
const hrSetupRoutes = require("./hrSetup.routes");
const hodSetupRoutes = require("./hodSetup.routes");
const hrHeadRoutes = require("./hrHead.routes");
const crmMasterRoutes = require("./crmMaster.routes");
const crmSetupRoutes = require("./crmSetup.routes");
const leadRoutes = require("./leads.routes");
const accountRoutes = require("./accounts.routes");
const visitRoutes = require("./visits.routes");
const productRoutes = require("./products.routes");
const orderRoutes = require("./orders.routes");
const salesReportRoutes = require("./salesReport.routes");
const followUpRoutes = require("./followUp.routes");
const locationRoutes = require("./location.routes");
const salesGeographyRoutes = require("./salesGeography.routes");
const salesGeographyAssignmentRoutes = require("./salesGeographyAssignment.routes");
const salesEmployeeLifecycleRoutes = require("./salesEmployeeLifecycle.routes");
const distributorSalesMappingRoutes = require("./distributorSalesMapping.routes");
const distributorReassignmentRoutes = require("./distributorReassignment.routes");
const channelMappingRoutes = require("./channelMapping.routes");
const salesTargetsRoutes = require("./salesTargets.routes");

const router = express.Router();

router.use("/auth", authRoutes);
router.use("/users", userRoutes);
router.use("/companies", companyRoutes);
router.use("/employee-requests", employeeRequestRoutes);
router.use("/notifications", notificationRoutes);
router.use("/attendance", attendanceRoutes);
router.use("/attendance/policies", attendancePolicyRoutes);
router.use("/shifts", shiftRoutes);
router.use("/holiday-calendars", holidayRoutes);
router.use("/leave", leaveRoutes);
router.use("/leaves", leaveRoutes);
router.use("/leave-types", leaveTypeRoutes);
router.use("/regularization", regularizationRoutes);
router.use("/weekly-off-policies", weeklyOffPolicyRoutes);
router.use("/leave-policies", leavePolicyRoutes);
router.use("/departments", departmentRoutes);
router.use("/designations", designationRoutes);
router.use("/reporting-managers", reportingManagerRoutes);
router.use("/org-tree", orgTreeRoutes);
router.use("/hr/setup", hrSetupRoutes);
router.use("/hod-setup", hodSetupRoutes);
router.use("/hr-head", hrHeadRoutes);
router.use("/crm/masters", crmMasterRoutes);
router.use("/crm/setup", crmSetupRoutes);
router.use("/crm/leads", leadRoutes);
router.use("/crm/accounts", accountRoutes);
router.use("/crm/visits", visitRoutes);
router.use("/crm/products", productRoutes);
router.use("/crm/orders", orderRoutes);
router.use("/crm/reports", salesReportRoutes);
router.use("/crm/followups", followUpRoutes);
router.use("/crm/location", locationRoutes);
router.use("/sales/geography", salesGeographyRoutes);
router.use("/sales/geography-assignments", salesGeographyAssignmentRoutes);
router.use("/sales/employee-transfers", salesEmployeeLifecycleRoutes);
router.use("/sales/distributor-mappings", distributorSalesMappingRoutes);
router.use("/sales/distributor-reassignments", distributorReassignmentRoutes);
router.use("/sales/channel-mappings", channelMappingRoutes);
router.use("/sales/targets", salesTargetsRoutes);

module.exports = router;
