const buildItems = (module, type, names) =>
    names.map((name, index) => ({
        module,
        type,
        name,
        code: name
            .toUpperCase()
            .replace(/[^A-Z0-9]+/g, "_")
            .replace(/^_+|_+$/g, ""),
        sortOrder: index + 1,
        isDefault: true,
        isSystem: true,
        isActive: true,
    }));

const DEFAULT_CRM_MASTERS = [
    ...buildItems("lead", "lead_source", [
        "New Lead",
        "Walk-In",
        "Referral",
        "Cold Call",
        "Social Media",
        "Exhibition",
        "Online Inquiry",
        "Dealer Reference",
        "Distributor Reference",
        "Existing Customer",
        "Website",
        "Email Campaign",
    ]),
    ...buildItems("lead", "lead_status", [
        "New",
        "Contacted",
        "Interested",
        "Follow-Up Scheduled",
        "Qualified",
        "Converted",
        "Lost",
        "Unqualified",
    ]),
    ...buildItems("lead", "lead_priority", ["Low", "Medium", "High", "Urgent"]),
    ...buildItems("lead", "lost_reason", [
        "Price Too High",
        "Competitor Chosen",
        "Not Interested",
        "Budget Constraint",
        "No Response",
        "Product Mismatch",
        "Timing Issue",
    ]),
    ...buildItems("visit", "visit_purpose", [
        "Introduction Visit",
        "Follow-Up Visit",
        "Product Demo",
        "Order Collection",
        "Payment Collection",
        "Complaint Resolution",
        "Dealer Audit",
        "Distributor Meeting",
    ]),
    ...buildItems("visit", "visit_outcome", [
        "Positive - Will Follow Up",
        "Order Taken",
        "Lead Created",
        "Demo Done",
        "Payment Collected",
        "Complaint Resolved",
        "Not Interested",
        "Not Available",
        "Revisit Needed",
        "Deal Closed",
    ]),
    ...buildItems("account", "account_type", [
        "Distributor",
        "Dealer",
        "Retailer",
        "Customer",
        "Corporate Client",
        "Channel Partner",
    ]),
    ...buildItems("account", "dealer_type", ["Authorized Dealer", "Sub-Dealer", "Direct Dealer"]),
    ...buildItems("account", "distributor_type", [
        "Regional Distributor",
        "National Distributor",
        "State Distributor",
        "Local Distributor",
    ]),
    ...buildItems("product", "uom", [
        "Piece",
        "Box",
        "Carton",
        "Kg",
        "Gram",
        "Litre",
        "Metre",
        "Set",
        "Pair",
        "Pack",
        "Dozen",
    ]),
    ...buildItems("product", "material_group", [
        "Raw Material",
        "Finished Goods",
        "Semi-Finished",
        "Spare Parts",
        "Trading Goods",
        "Services",
    ]),
    ...buildItems("product", "material_type", [
        "Finished Product",
        "Raw Material",
        "Service",
        "Trading",
        "Packaging",
    ]),
    ...buildItems("product", "division", ["General"]),
    ...buildItems("product", "mrp_type", ["MRP", "Reorder Point", "Manual", "No Planning"]),
    ...buildItems("product", "procurement_type", ["In-House", "External", "Both"]),
    ...buildItems("product", "price_control", ["Standard Price", "Moving Average Price"]),
    ...buildItems("product", "tax_classification", ["Taxable", "Exempt", "Zero Rated"]),
    ...buildItems("order", "order_status", [
        "Draft",
        "Confirmed",
        "Processing",
        "Dispatched",
        "Delivered",
        "Cancelled",
        "On Hold",
    ]),
    ...buildItems("order", "payment_status", ["Pending", "Partial", "Paid", "Overdue", "Waived"]),
    ...buildItems("order", "discount_type", ["Percentage", "Fixed Amount", "None"]),
    ...buildItems("general", "currency", ["INR", "USD", "EUR", "GBP", "AED"]),
    ...buildItems("general", "country", [
        "India",
        "United States",
        "United Arab Emirates",
        "United Kingdom",
        "Canada",
        "Australia",
        "Germany",
        "France",
        "Singapore",
        "Japan",
    ]),
];

module.exports = {
    DEFAULT_CRM_MASTERS,
};
