const CHANNEL_MAPPING_MANAGE_ROLES = Object.freeze([
  "super_admin",
  "company_admin",
  "sales_head",
]);

const CHANNEL_MAPPING_READ_ROLES = Object.freeze([
  ...CHANNEL_MAPPING_MANAGE_ROLES,
  "sub_admin",
  "sales_manager",
  "sales_executive",
  "sales",
]);

const CHANNEL_ACCOUNT_TYPES = Object.freeze({
  DISTRIBUTOR: "DISTRIBUTOR",
  DEALER: "DEALER",
  RETAILER: "RETAILER",
  CUSTOMER: "CUSTOMER",
});

const CHANNEL_READINESS_STATES = Object.freeze({
  MAPPED_VALID: "MAPPED_VALID",
  UNMAPPED: "UNMAPPED",
  READY_FOR_MAPPING: "READY_FOR_MAPPING",
  LEGACY_ACTIVE_UNMAPPED: "LEGACY_ACTIVE_UNMAPPED",
  INVALID_PARENT_TYPE: "INVALID_PARENT_TYPE",
  INVALID_RELATIONSHIP_TYPE: "INVALID_RELATIONSHIP_TYPE",
  PARENT_MISSING: "PARENT_MISSING",
  CHANNEL_PARENT_INACTIVE: "CHANNEL_PARENT_INACTIVE",
  PARENT_DISTRIBUTOR_INACTIVE: "PARENT_DISTRIBUTOR_INACTIVE",
  PARENT_DISTRIBUTOR_UNMAPPED: "PARENT_DISTRIBUTOR_UNMAPPED",
  PARENT_DISTRIBUTOR_REASSIGNMENT_REQUIRED: "PARENT_DISTRIBUTOR_REASSIGNMENT_REQUIRED",
  CROSS_COMPANY_PARENT: "CROSS_COMPANY_PARENT",
  LEGACY_DIRECT_DISTRIBUTOR_CUSTOMER: "LEGACY_DIRECT_DISTRIBUTOR_CUSTOMER",
});

module.exports = {
  CHANNEL_MAPPING_MANAGE_ROLES,
  CHANNEL_MAPPING_READ_ROLES,
  CHANNEL_ACCOUNT_TYPES,
  CHANNEL_READINESS_STATES,
};
