const REASSIGNMENT_ROLES = Object.freeze([
  "super_admin",
  "company_admin",
  "sales_head",
  "sales_manager",
]);

const REQUEST_STATUSES = Object.freeze({
  PENDING: "PENDING",
  APPROVED: "APPROVED",
  REJECTED: "REJECTED",
  CANCELLED: "CANCELLED",
  APPLIED: "APPLIED",
});

const APPROVAL_LEVELS = Object.freeze({
  ASM: "ASM",
  BRANCH_MANAGER: "BRANCH_MANAGER",
  RSM: "RSM",
  ZSM: "ZSM",
  HEAD_OF_SALES: "HEAD_OF_SALES",
  PLATFORM_ADMIN: "PLATFORM_ADMIN",
});

const BOUNDARY_TYPES = Object.freeze({
  SAME_AREA: "SAME_AREA",
  CROSS_AREA_SAME_BRANCH: "CROSS_AREA_SAME_BRANCH",
  CROSS_BRANCH_SAME_REGION: "CROSS_BRANCH_SAME_REGION",
  CROSS_REGION_SAME_ZONE: "CROSS_REGION_SAME_ZONE",
  CROSS_ZONE: "CROSS_ZONE",
});

const REASSIGNMENT_CODES = Object.freeze({
  NO_CURRENT_MAPPING: "NO_CURRENT_MAPPING",
  DATA_INTEGRITY_CONFLICT: "DATA_INTEGRITY_CONFLICT",
  ASSIGNEE_MIRROR_CONFLICT: "ASSIGNEE_MIRROR_CONFLICT",
  SAME_FSD_NOT_REASSIGNMENT: "SAME_FSD_NOT_REASSIGNMENT",
  CROSS_AREA_REASSIGNMENT_NOT_SUPPORTED_IN_PHASE_5A: "CROSS_AREA_REASSIGNMENT_NOT_SUPPORTED_IN_PHASE_5A",
  ACTIVE_REQUEST_EXISTS: "ACTIVE_REASSIGNMENT_REQUEST_EXISTS",
  REQUEST_STALE: "REQUEST_STALE",
  REQUEST_STALE_CURRENT_MAPPING_CHANGED: "REQUEST_STALE_CURRENT_MAPPING_CHANGED",
  REQUEST_STALE_NEW_FSD_GEOGRAPHY_CHANGED: "REQUEST_STALE_NEW_FSD_GEOGRAPHY_CHANGED",
  REQUEST_STALE_BOUNDARY_CHANGED: "REQUEST_STALE_BOUNDARY_CHANGED",
  ASM_VACANT_HEAD_APPROVAL_REQUIRED: "ASM_VACANT_HEAD_APPROVAL_REQUIRED",
  MAKER_CHECKER_HEAD_APPROVAL_REQUIRED: "MAKER_CHECKER_HEAD_APPROVAL_REQUIRED",
  HEAD_OVERRIDE_REASON_REQUIRED: "HEAD_OVERRIDE_REASON_REQUIRED",
  CURRENT_AREA_ASM_APPROVAL_REQUIRED: "CURRENT_AREA_ASM_APPROVAL_REQUIRED",
  DISTRIBUTOR_INACTIVE: "DISTRIBUTOR_INACTIVE",
  DESTINATION_AREA_REQUIRED: "DESTINATION_AREA_REQUIRED",
  DESTINATION_AREA_MUST_DIFFER: "DESTINATION_AREA_MUST_DIFFER_FOR_PHASE_5B",
  REQUIRED_APPROVER_VACANT_HEAD_APPROVAL_REQUIRED: "REQUIRED_APPROVER_VACANT_HEAD_APPROVAL_REQUIRED",
  CURRENT_BOUNDARY_MANAGER_APPROVAL_REQUIRED: "CURRENT_BOUNDARY_MANAGER_APPROVAL_REQUIRED",
});

module.exports = {
  REASSIGNMENT_ROLES,
  REQUEST_STATUSES,
  APPROVAL_LEVELS,
  BOUNDARY_TYPES,
  REASSIGNMENT_CODES,
};
