const DISTRIBUTOR_MAPPING_MANAGE_ROLES = Object.freeze([
  "super_admin",
  "company_admin",
  "sales_head",
]);

const DISTRIBUTOR_MAPPING_STATES = Object.freeze({
  MAPPED_VALID: "MAPPED_VALID",
  UNMAPPED: "UNMAPPED",
  LEGACY_ACTIVE_UNMAPPED: "LEGACY_ACTIVE_UNMAPPED",
  INVALID_ACCOUNT_TYPE: "INVALID_ACCOUNT_TYPE",
  NO_PRIMARY_FSD: "NO_PRIMARY_FSD",
  FSD_INACTIVE: "FSD_INACTIVE",
  FSD_AMBIGUOUS: "FSD_AMBIGUOUS",
  PRIMARY_FSD_INACTIVE: "PRIMARY_FSD_INACTIVE",
  PRIMARY_FSD_UNASSIGNED: "PRIMARY_FSD_UNASSIGNED",
  PRIMARY_FSD_GEOGRAPHY_MISMATCH: "PRIMARY_FSD_GEOGRAPHY_MISMATCH",
  GEOGRAPHY_INACTIVE: "GEOGRAPHY_INACTIVE",
  SUPERVISORY_VACANCY: "SUPERVISORY_VACANCY",
  EXISTING_ASSIGNEE_CONFLICT: "EXISTING_ASSIGNEE_CONFLICT",
  ASSIGNEE_MIRROR_CONFLICT: "ASSIGNEE_MIRROR_CONFLICT",
  CURRENT_MAPPING_EXISTS: "CURRENT_MAPPING_EXISTS",
  REASSIGNMENT_REQUIRED: "REASSIGNMENT_REQUIRED",
});

const SUPERVISORY_VACANCY_CODES = Object.freeze({
  2: "ASM_VACANT",
  3: "BRANCH_MANAGER_VACANT",
  4: "RSM_VACANT",
  5: "ZSM_VACANT",
  6: "HEAD_OF_SALES_VACANT",
});

module.exports = {
  DISTRIBUTOR_MAPPING_MANAGE_ROLES,
  DISTRIBUTOR_MAPPING_STATES,
  SUPERVISORY_VACANCY_CODES,
};
