const PERMISSION_CATALOG = {
  "crm.visits.start": { label: "Start Field Visit", module: "CRM" },
  "crm.visits.end": { label: "End Field Visit", module: "CRM" },
  "crm.visits.view.team": { label: "View Team Visits", module: "CRM" },
  "crm.visits.view.company": { label: "View All Company Visits", module: "CRM" },
  "crm.visits.approve": { label: "Approve Flagged Visits", module: "CRM" },
  "crm.leads.create": { label: "Create Leads", module: "CRM" },
  "crm.leads.view.own": { label: "View Own Leads", module: "CRM" },
  "crm.leads.convert": { label: "Convert Leads", module: "CRM" },
  "crm.leads.followup.create": { label: "Create Lead Follow-Ups", module: "CRM" },
  "crm.leads.followup.complete": { label: "Complete Lead Follow-Ups", module: "CRM" },
  "crm.leads.followup.view": { label: "View Lead Follow-Ups", module: "CRM" },
  "crm.leads.activity.log": { label: "Log Lead Activities", module: "CRM" },
  "crm.orders.create": { label: "Create Orders", module: "CRM" },
  "crm.orders.view.team": { label: "View Team Orders", module: "CRM" },
  "crm.orders.view.company": { label: "View All Orders", module: "CRM" },
  "crm.products.view": { label: "View Product Master", module: "CRM" },
  "crm.products.manage": { label: "Manage Product Master", module: "CRM" },
  "crm.accounts.view": { label: "View Accounts", module: "CRM" },
  "crm.accounts.manage": { label: "Create/Edit Accounts", module: "CRM" },
  "crm.masters.manage": { label: "Manage CRM Masters", module: "CRM" },
  "crm.reports.visits": { label: "View Visit Reports", module: "CRM" },
  "crm.reports.products": { label: "View Product Reports", module: "CRM" },
  "crm.reports.head": { label: "View Head-Level Reports", module: "CRM" },
};

const DEFAULT_ROLE_PERMISSIONS = {
  sales_executive: [
    "crm.visits.start",
    "crm.visits.end",
    "crm.leads.create",
    "crm.leads.view.own",
    "crm.leads.convert",
    "crm.leads.followup.create",
    "crm.leads.followup.complete",
    "crm.leads.followup.view",
    "crm.leads.activity.log",
    "crm.orders.create",
    "crm.accounts.view",
    "crm.products.view",
  ],
  sales_manager: [
    "crm.visits.start",
    "crm.visits.end",
    "crm.leads.create",
    "crm.leads.view.own",
    "crm.leads.convert",
    "crm.leads.followup.create",
    "crm.leads.followup.complete",
    "crm.leads.followup.view",
    "crm.leads.activity.log",
    "crm.orders.create",
    "crm.accounts.view",
    "crm.products.view",
    "crm.visits.view.team",
    "crm.orders.view.team",
    "crm.reports.visits",
    "crm.visits.approve",
  ],
  sales_head: [
    "crm.visits.start",
    "crm.visits.end",
    "crm.leads.create",
    "crm.leads.view.own",
    "crm.leads.convert",
    "crm.orders.create",
    "crm.leads.followup.create",
    "crm.leads.followup.complete",
    "crm.leads.followup.view",
    "crm.leads.activity.log",
    "crm.accounts.view",
    "crm.products.view",
    "crm.visits.view.team",
    "crm.orders.view.team",
    "crm.reports.visits",
    "crm.visits.approve",
    "crm.visits.view.company",
    "crm.orders.view.company",
    "crm.reports.products",
    "crm.reports.head",
    "crm.masters.manage",
  ],
};

module.exports = {
  PERMISSION_CATALOG,
  DEFAULT_ROLE_PERMISSIONS,
};
