const SALES_VISIBILITY_SCOPE = Object.freeze({
  COMPANY_SALES: "COMPANY_SALES",
  ZONE: "ZONE",
  REGION: "REGION",
  BRANCH: "BRANCH",
  AREA: "AREA",
  OWN_ASSIGNED: "OWN_ASSIGNED",
  NONE: "NONE",
});

const SALES_VISIBILITY_STATUS = Object.freeze({
  READY: "READY",
  NO_ACTIVE_SALES_GEOGRAPHY: "NO_ACTIVE_SALES_GEOGRAPHY",
  AMBIGUOUS_SALES_DESIGNATION: "AMBIGUOUS_SALES_DESIGNATION",
  INVALID_SALES_GEOGRAPHY: "INVALID_SALES_GEOGRAPHY",
  NOT_SALES_AUTHORITY: "NOT_SALES_AUTHORITY",
});

const LEVEL_SCOPE = Object.freeze({
  1: SALES_VISIBILITY_SCOPE.OWN_ASSIGNED,
  2: SALES_VISIBILITY_SCOPE.AREA,
  3: SALES_VISIBILITY_SCOPE.BRANCH,
  4: SALES_VISIBILITY_SCOPE.REGION,
  5: SALES_VISIBILITY_SCOPE.ZONE,
  6: SALES_VISIBILITY_SCOPE.COMPANY_SALES,
});

const LEVEL_GEOGRAPHY = Object.freeze({
  1: "AREA",
  2: "AREA",
  3: "BRANCH",
  4: "REGION",
  5: "ZONE",
});

module.exports = {
  SALES_VISIBILITY_SCOPE,
  SALES_VISIBILITY_STATUS,
  LEVEL_SCOPE,
  LEVEL_GEOGRAPHY,
};
