const METRIC_CODE = "ORDER_VALUE_EX_TAX_AFTER_DISCOUNT";

const SALES_PERFORMANCE = Object.freeze({
  METRIC_CODE,
  METRIC_LABEL: "Order Booking",
  TRIGGER: "ORDER_CREATED",
  VALUE_BASIS: "DISCOUNTED_EX_TAX",
  PERIOD_TYPE: "MONTH",
  ALLOCATION_POLICY: "CONTROLLED_FLEXIBLE",
  ATTRIBUTION_POLICY: "TRANSACTION_TIME",
  DEFAULT_CURRENCY: "INR",
  DEFAULT_TIMEZONE: "Asia/Kolkata",
  DEFAULT_FISCAL_START_MONTH: 4,
});

const POLICY_STATUSES = ["DRAFT", "ACTIVE", "INACTIVE"];
const PLAN_STATUSES = ["DRAFT", "SUBMITTED", "ACTIVE", "REJECTED", "SUPERSEDED"];
const OWNER_TYPES = ["COMPANY", "ZONE", "REGION", "BRANCH", "AREA", "EMPLOYEE_FSD", "DISTRIBUTOR"];
const OWNER_CHILDREN = Object.freeze({
  COMPANY: ["ZONE"],
  ZONE: ["REGION"],
  REGION: ["BRANCH"],
  BRANCH: ["AREA"],
  AREA: ["EMPLOYEE_FSD"],
  EMPLOYEE_FSD: ["DISTRIBUTOR"],
  DISTRIBUTOR: [],
});
const ATTRIBUTION_CONFIDENCE = ["EXACT", "INFERRED", "UNATTRIBUTABLE"];

module.exports = {
  SALES_PERFORMANCE,
  POLICY_STATUSES,
  PLAN_STATUSES,
  OWNER_TYPES,
  OWNER_CHILDREN,
  ATTRIBUTION_CONFIDENCE,
};
