const SALES_LEVEL_GEOGRAPHY_TYPE = Object.freeze({
  5: "ZONE",
  4: "REGION",
  3: "BRANCH",
  2: "AREA",
  1: "AREA",
});

const SALES_ASSIGNMENT_MANAGE_ROLES = Object.freeze([
  "super_admin",
  "company_admin",
  "sales_head",
]);

const SALES_ASSIGNMENT_OWN_READ_ROLES = Object.freeze([
  "sales_head",
  "sales_manager",
  "sales_executive",
]);

const ASSIGNMENT_READINESS = Object.freeze({
  READY: "READY",
  UNASSIGNED: "UNASSIGNED",
  AMBIGUOUS_DESIGNATION: "AMBIGUOUS_DESIGNATION",
  MISSING_LEVEL: "MISSING_LEVEL",
  REPORTING_CONFLICT: "REPORTING_CONFLICT",
  INACTIVE: "INACTIVE",
  NOT_APPLICABLE: "NOT_APPLICABLE",
});

const REPORTING_COMPATIBILITY = Object.freeze({
  COMPATIBLE: "COMPATIBLE",
  NO_MANAGER: "NO_MANAGER",
  MANAGER_NOT_ASSIGNED: "MANAGER_NOT_ASSIGNED",
  GEOGRAPHY_MISMATCH: "GEOGRAPHY_MISMATCH",
  MANAGER_LEVEL_INVALID: "MANAGER_LEVEL_INVALID",
  CROSS_DEPARTMENT: "CROSS_DEPARTMENT",
  LEGACY_ASSIGNMENT_CONFLICT: "LEGACY_ASSIGNMENT_CONFLICT",
});

const isResponsibleManagementLevel = (level) => [2, 3, 4, 5].includes(Number(level));

module.exports = {
  SALES_LEVEL_GEOGRAPHY_TYPE,
  SALES_ASSIGNMENT_MANAGE_ROLES,
  SALES_ASSIGNMENT_OWN_READ_ROLES,
  ASSIGNMENT_READINESS,
  REPORTING_COMPATIBILITY,
  isResponsibleManagementLevel,
};
